{
    "levelname": "INFO",
    "levelno": 20,
    "name": "test",
    "module": "test",
    "filename": "test.py",
    "lineno": 18,
    "funcName": "<module>",
    "pathname": "/home/smz/projects/fancylogging/test.py",
    "message": "Info message",
    "msg": "Info message",
    "created": 1706087594.6466918,
    "asctime": "2024-01-24 10:13:14,646",
    "process": 1443630,
    "processName": "MainProcess",
    "exc_info": null,
    "stack_info": null
}
{
    "levelname": "DEBUG",
    "levelno": 10,
    "name": "test",
    "module": "test",
    "filename": "test.py",
    "lineno": 19,
    "funcName": "<module>",
    "pathname": "/home/smz/projects/fancylogging/test.py",
    "message": "Debug message",
    "msg": "Debug message",
    "created": 1706087594.6489952,
    "asctime": "2024-01-24 10:13:14,648",
    "process": 1443630,
    "processName": "MainProcess",
    "exc_info": null,
    "stack_info": null
}
{
    "levelname": "WARNING",
    "levelno": 30,
    "name": "test",
    "module": "test",
    "filename": "test.py",
    "lineno": 20,
    "funcName": "<module>",
    "pathname": "/home/smz/projects/fancylogging/test.py",
    "message": "Warning message",
    "msg": "Warning message",
    "created": 1706087594.649051,
    "asctime": "2024-01-24 10:13:14,649",
    "process": 1443630,
    "processName": "MainProcess",
    "exc_info": null,
    "stack_info": null
}
{
    "levelname": "ERROR",
    "levelno": 40,
    "name": "test",
    "module": "test",
    "filename": "test.py",
    "lineno": 21,
    "funcName": "<module>",
    "pathname": "/home/smz/projects/fancylogging/test.py",
    "message": "Error message",
    "msg": "Error message",
    "created": 1706087594.6498053,
    "asctime": "2024-01-24 10:13:14,649",
    "process": 1443630,
    "processName": "MainProcess",
    "exc_info": null,
    "stack_info": null
}
{
    "levelname": "CRITICAL",
    "levelno": 50,
    "name": "test",
    "module": "test",
    "filename": "test.py",
    "lineno": 22,
    "funcName": "<module>",
    "pathname": "/home/smz/projects/fancylogging/test.py",
    "message": "Critical message",
    "msg": "Critical message",
    "created": 1706087594.65043,
    "asctime": "2024-01-24 10:13:14,650",
    "process": 1443630,
    "processName": "MainProcess",
    "exc_info": null,
    "stack_info": null
}
{
    "levelname": "ERROR",
    "levelno": 40,
    "name": "test",
    "module": "test",
    "filename": "test.py",
    "lineno": 26,
    "funcName": "<module>",
    "pathname": "/home/smz/projects/fancylogging/test.py",
    "message": "Exception message",
    "msg": "Exception message",
    "created": 1706087594.6510363,
    "asctime": "2024-01-24 10:13:14,651",
    "process": 1443630,
    "processName": "MainProcess",
    "exc_info": "Traceback (most recent call last):\n  File \"/home/smz/projects/fancylogging/test.py\", line 24, in <module>\n    raise Exception(\"Raising a test exception in main\")\nException: Raising a test exception in main",
    "stack_info": null
}